{
 "title": "Arbitrage Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Oportunities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "arbitrage_opportunities_found_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Difference Guage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "price_difference_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum[5m]) / ignoring(le) rate(django_http_requests_latency_seconds_by_view_method_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}