# Generated by Django 5.2.7 on 2025-10-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('binance_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('gateio_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_difference_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
